version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PGPASSWORD: ${PGPASSWORD}
      TZ: "Asia/Tokyo"
    ports:
      - "127.0.0.1:${PORT_POSTGRES}:5432"
    networks:
      - nw_scp-jp-sys
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./install/postgres/init:/docker-entrypoint-initdb.d
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "127.0.0.1:${PORT_PGADMIN}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - nw_scp-jp-sys
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: always

  api:
    build: install/api
    volumes:
      - ./api:/app
    ports:
      - "127.0.0.1:${PORT_LOCAL_API}:80"
    networks:
      - nw_scp-jp-sys
    depends_on:
      - postgres
    env_file:
      - api-config.env
      - .env
    restart: always

volumes:
  api:
  postgres:
  pgadmin:


networks:
  nw_scp-jp-sys:
    driver: bridge