-- create application_users group
CREATE ROLE application_users WITH
  NOLOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

-- create api user
-- pass: Lqckon!wjLMBmsN!9aZPfuN8c
CREATE ROLE api WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:+PrVjqPm6q/h7xWdAVW0wA==$xmR8eQ7NXq171HvLFcPF9xuD1/1dHwGrVuDkFz34PFY=:KJomXHIzBXscdCb0aJkh7Ljs/ZvdpufH8ChRlr/hm8A=';

GRANT application_users TO api;

COMMENT ON ROLE api IS 'SCP-JP-Sys API user';